resources:

  - name: S_Bash_0397_FileSpec
    type: FileSpec
    configuration:
      sourceArtifactory: art_v
      aql: "{"repo":"example-repo-local"}"      
pipelines:

  - name: pipelines_S_Bash_0397
    steps:
      - name: S_Bash_0397
        type: Bash
        configuration:
          inputResources:
            - name: S_Bash_0397_FileSpec
        execution:
          onExecute:
            - echo "executing step..."
