#pipelines:
#  - name: windows_pipelines
#    steps:
#      - name: windows_pipelines_0001
#        type: PowerShell
#        execution:
#          onExecute:
#            - echo "executing step..."


resources:
  - name: myRepo
    type: GitRepo
    configuration:
      gitProvider: github
      path: jbharath-code/windows-step

pipelines:
  - name: vijay_pipeline
    steps:  
      - name: functions
        type: PowerShell 
        configuration:
          inputResources:
            - name: myRepo
        execution:
          onExecute:
            - Push-Location $res_myRepo_resourcePath
            - get-childitem $res_myRepo_resourcePath
            - find_resource_variable myRepo $res_myRepo_resourcePath
            - New-Item -Path 'C:\Users\Administrator\Documents\hello.txt' -ItemType File 
            - 'Hello world! This is the first line of my file.' | out-file -filepath C:\Users\Administrator\Documents\hello.txt 
            - add_run_files -sources "C:\Users\Administrator\Documents\hello.txt" -name repo_pipe   
            - add_pipeline_files -sources "C:\Users\Administrator\Documents\hello.txt" -name vijay                
      - name: functions2
        type: PowerShell 
        configuration:
          inputSteps:
            - name: functions
        execution:
          onExecute:
            - get-childitem $res_myRepo_resourcePath    
            - restore_run_files -name repo_pipe -path $step_tmp_dir   
            - get-childitem $res_myRepo_resourcePath     
      - name: functions3
        type: PowerShell 
        configuration:
          inputSteps:
            - name: functions2
        execution:
          onExecute:
            - get-childitem $res_myRepo_resourcePath                        
            - restore_pipeline_files -name vijay -path $step_tmp_dir
            - get-childitem $step_tmp_dir
