resources:

  - name: S_Bash_0397_FileSpec
    type: FileSpec
    configuration:
      sourceArtifactory: artifactory
      aql: items.find({"name":{"$match":"pipelines_1599764926/projects/1/pipelines/2/runs/1/steps/1/1.tar.gz"}})
pipelines:

  - name: pipelines_S_Bash_0397
    steps:
      - name: S_Bash_0397
        type: Bash
        configuration:
          inputResources:
            - name: S_Bash_0397_FileSpec
        execution:
          onExecute:
            - echo "executing step..."
