resources:

  - name: S_Bash_0397_FileSpec
    type: FileSpec
    configuration:
      sourceArtifactory: artifactory
      aql: '{"items.find":{"name":{"$match":"pipelines_1599646149/projects/1/pipelines/3/stepConsoles/5/step_6_consoles*"}}}'
pipelines:

  - name: pipelines_S_Bash_0397
    steps:
      - name: S_Bash_0397
        type: Bash
        configuration:
          inputResources:
            - name: S_Bash_0397_FileSpec
        execution:
          onExecute:
            - echo "executing step..."
