resources:

  - name: S_Bash_0397_FileSpec
    type: FileSpec
    configuration:
      sourceArtifactory: artifactory
      aql: items.find({"path":{"$eq":"pipelines_1599646149/"}}

pipelines:

  - name: pipelines_S_Bash_0397
    steps:
      - name: S_Bash_0397
        type: Bash
        configuration:
          inputResources:
            - name: S_Bash_0397_FileSpec
        execution:
          onExecute:
            - echo "executing step..."
