resources:

  - name: S_PS_R_FLSPEC_0001_FileSpec
    type: FileSpec
    configuration:
      sourceArtifactory: s_artifactory
      aql: '{"items.find":{"modified":{"$last":"3d"}}}'
      recursive: false

pipelines:

  - name: pipelines_S_PS_R_FLSPEC_0001
    steps:
      - name: S_PS_R_FLSPEC_0001
        type: PowerShell
        configuration:
          nodePool: windows
          inputResources:
            - name: S_PS_R_FLSPEC_0001_FileSpec
              trigger: true
        execution:
          onExecute:
            - write-output "executing step..."
