resources:
  - name: S_PS_R_FLSPEC_0018
    type: FileSpec
    configuration:
      sourceArtifactory: art_v
      aql: '{"items.find":{"name":{"$match":"s_foo*"}}}'
pipelines:
  - name: pipelines_S_PS_R_FLSPEC_0018
    steps:
      - name: S_PS_R_FLSPEC_0018
        type: PowerShell
        configuration:
          nodePool: windows-static
          inputResources:
            - name: S_PS_R_FLSPEC_0018
        execution:
          onExecute:
            - write-output "executing step..."
            - if (Test-Path "testing/s_foo"){ Write-Output "successful"}
