resources:
  - name: S_PS_R_FLSPEC_0018
    type: FileSpec
    configuration:
      sourceArtifactory: art_v
      aql: '{"items.find":{"modified":{"$last":"3d"}}}'
pipelines:
  - name: pipelines_S_PS_R_FLSPEC_0018
    steps:
      - name: S_PS_R_FLSPEC_0018
        type: PowerShell
        configuration:
          nodePool: win_2019
          inputResources:
            - name: S_PS_R_FLSPEC_0018
        execution:
          onExecute:
            - write-output "executing step..."
